In [7]:
import pandas as pd

In [16]:
ds = pd.read_csv('ceramic_production_measurements_reduced.csv')
ds.columns

Index(['Temperature (°C)', 'Pressure (kPa)', 'EC-Messwert'], dtype='object')

# testing AP

In [1]:
from autoprognosis.explorers.core.defaults import default_regressors_names
default_regressors_names

['random_forest_regressor',
 'xgboost_regressor',
 'linear_regression',
 'catboost_regressor']

In [14]:
from autoprognosis.studies.regression import RegressionStudy
from autoprognosis.explorers.core.defaults import default_regressors_names
from sklearn.utils.validation import check_X_y
import numpy as np
import pandas as pd
from pathlib import Path

working_directory = Path.cwd() / "workdir"

def formate_dataset(name, ds, target):
    dataset = {}
    ds['target'] = ds[target]
    dataset[name] = (ds.drop(columns=[target, 'target']), ds['target'])
    return dataset

fake_ds = pd.read_csv('ceramic_production_measurements_reduced.csv')
fake_ds_pd = formate_dataset('edgecurl' ,fake_ds, 'EC-Messwert')

X, y = fake_ds_pd['edgecurl']

X, y = check_X_y(X, y, accept_sparse=True)

feature_names = [f"f{i}" for i in range(X.shape[1])]
feature_names.insert(0, 'target')

train_data = pd.DataFrame(
    np.hstack((np.array(y)[:, np.newaxis], X)),
    columns=feature_names
)

model_names = ['linear_regression', 'catboost_regressor']
# study = RegressionStudy(
#     train_data,
#     target='target',
#     workspace=working_directory,
#     score_threshold=-1.0,
#     regressors=model_names,
#     timeout=int(60 / len(model_names)),
#     random_state=42,
# )
study = RegressionStudy(
    dataset=train_data,  # pandas DataFrame
    target="target",  # the label column in the dataset
    workspace=working_directory,
    regressors=model_names,
    timeout=int(60 / len(model_names)),
    random_state=42,
    score_threshold=-1.0,
)
model = study.fit()


in load progress
---------------------259----------------------------------
search_X.shape: (500, 2)
search_Y.shape: (500,)
----------------------------------------------------------
model not pretrained
index: 0
model: <autoprognosis.plugins.ensemble.regression.WeightedRegressionEnsemble object at 0x00000253756C2670>
preds: (100, 1)
X_test.shape: (100, 2)
Y_test.shape: (100,)
model not pretrained
index: 1
model: <autoprognosis.plugins.ensemble.regression.WeightedRegressionEnsemble object at 0x00000253756C2DF0>
preds: (100, 1)
X_test.shape: (100, 2)
Y_test.shape: (100,)
model not pretrained
index: 2
model: <autoprognosis.plugins.ensemble.regression.WeightedRegressionEnsemble object at 0x0000025377E929D0>
preds: (100, 1)
X_test.shape: (100, 2)
Y_test.shape: (100,)
model not pretrained
index: 3
model: <autoprognosis.plugins.ensemble.regression.WeightedRegressionEnsemble object at 0x0000025377E924C0>
preds: (100, 1)
X_test.shape: (100, 2)
Y_test.shape: (100,)
model not pretrained
index: 4

In [10]:
study.output_file

WindowsPath('d:/Master/2.semester/Forschung/git/TabMini/workdir/18321159723536856664/model.p')

# auto sklearn

# H2O

In [1]:

import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split, GridSearchCV, cross_validate

import h2o
from h2o.automl import H2OAutoML
from h2o.sklearn import H2OAutoMLRegressor



In [51]:
def formate_dataset(name, ds, target):
    dataset = {}
    ds['target'] = ds[target]
    dataset[name] = (ds.drop(columns=[target, 'target']), ds['target'])
    return dataset

fake_ds = pd.read_csv('ceramic_production_measurements_reduced.csv')
fake_ds_pd = formate_dataset('edgecurl' ,fake_ds, 'EC-Messwert')

X, y = fake_ds_pd['edgecurl']

In [52]:
X = pd.DataFrame(X.to_numpy(), columns= X.columns)
X

Temperature (°C)  Pressure (kPa)
0          449.448143     1901.428613
1          942.211154      399.347564
2         1163.501553     1550.265647
3          874.808602     1542.540693
4           37.715023     1272.820823
..                ...             ...
495        901.114072      127.846328
496        892.484178     1056.116844
497        998.670937      917.536580
498       1052.230300     1563.444532
499        419.337169      425.246379

[500 rows x 2 columns]

In [54]:
len(y.to_numpy()), len(X)

(500, 500)

In [2]:

ds = datasets.fetch_california_housing()
# converting the data into a pandas DataFrame as we need the column names for the monotone_constraints parameter
X = pd.DataFrame(ds.data, columns=ds.feature_names)
y = ds.target
X

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

## automl regressor

In [14]:
seed = 2020
regressor = H2OAutoMLRegressor(seed=seed, max_runtime_secs=60)

# regressor = cross_validate(
#             regressor,
#             X,
#             y,
#             cv=2,
#             scoring='neg_mean_absolute_error',
#             n_jobs=1,
#             return_train_score=True,
#             return_estimator=True
#         )
regressor = regressor.fit(X,y)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
AutoML progress: |
17:28:28.474: AutoML: XGBoost is not available; skipping it.

███████████████████████████████████████████████████████████████| (done) 100%


In [90]:
X.loc[50].to_numpy()

array([   0.9218    ,   21.        ,    2.0456621 ,    1.03424658,
        735.        ,    1.67808219,   37.82      , -122.27      ])

In [8]:
regressor.leaderboard

AttributeError: 'H2OAutoMLRegressor' object has no attribute 'leaderboard'

In [108]:
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [109]:
regressor['estimator'][1].predict(X.loc[50].to_numpy()), regressor['estimator'][0].predict(X.loc[50].to_numpy())

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
stackedensemble prediction progress: |███████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
stackedensemble prediction progress: |

c:\Users\3aboo\miniconda3\envs\tabmini\lib\site-packages\h2o\frame.py:1981: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"


███████████████████████████████████████████| (done) 100%


c:\Users\3aboo\miniconda3\envs\tabmini\lib\site-packages\h2o\frame.py:1981: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"


(array([1.30303024, 3.64604928, 1.36830772, 1.24792132, 3.64604928,
        1.31665111, 3.64604928, 1.65235889]),
 array([1.17345677, 4.06348216, 1.18820496, 1.12319111, 4.83943286,
        1.16256719, 4.08176886, 1.15566042]))

In [117]:
regressor['estimator'][0].leaderboard

AttributeError: 'H2OAutoMLRegressor' object has no attribute 'leaderboard'

## normal regressor

In [26]:
ds

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [3]:
train_df = pd.DataFrame(ds.data, columns=[ds.feature_names])
train_df['target'] = ds.target
train_df

MedInc HouseAge  AveRooms AveBedrms Population  AveOccup Latitude  \
0      8.3252     41.0  6.984127  1.023810      322.0  2.555556    37.88   
1      8.3014     21.0  6.238137  0.971880     2401.0  2.109842    37.86   
2      7.2574     52.0  8.288136  1.073446      496.0  2.802260    37.85   
3      5.6431     52.0  5.817352  1.073059      558.0  2.547945    37.85   
4      3.8462     52.0  6.281853  1.081081      565.0  2.181467    37.85   
...       ...      ...       ...       ...        ...       ...      ...   
20635  1.5603     25.0  5.045455  1.133333      845.0  2.560606    39.48   
20636  2.5568     18.0  6.114035  1.315789      356.0  3.122807    39.49   
20637  1.7000     17.0  5.205543  1.120092     1007.0  2.325635    39.43   
20638  1.8672     18.0  5.329513  1.171920      741.0  2.123209    39.43   
20639  2.3886     16.0  5.254717  1.162264     1387.0  2.616981    39.37   

      Longitude target  
0       -122.23  4.526  
1       -122.22  3.585  
2       -122.24  3.521  
3       -122.25  3.413  
4       -122.25  3.422  
...         ...    ...  
20635   -121.09  0.781  
20636   -121.21  0.771  
20637   -121.22  0.923  
20638   -121.32  0.847  
20639   -121.24  0.894  

[20640 rows x 9 columns]

In [4]:
h2o.init()

# Assuming train_df is your training data as a pandas DataFrame
train_h2o_frame = h2o.H2OFrame(train_df)
train_h2o_frame

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
; OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
  Starting server from C:\Users\3aboo\miniconda3\envs\tabmini\Lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\3aboo\AppData\Local\Temp\tmpitibgueg
  JVM stdout: C:\Users\3aboo\AppData\Local\Temp\tmpitibgueg\h2o_3aboo_started_from_python.out
  JVM stderr: C:\Users\3aboo\AppData\Local\Temp\tmpitibgueg\h2o_3aboo_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.


--------------------------  -----------------------------
H2O_cluster_uptime:         02 secs
H2O_cluster_timezone:       Europe/Berlin
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.4
H2O_cluster_version_age:    1 month and 12 days
H2O_cluster_name:           H2O_from_python_3aboo_c7uqw3
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    2.961 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.9.19 final
--------------------------  -----------------------------

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%


('MedInc',)    ('HouseAge',)    ('AveRooms',)    ('AveBedrms',)    ('Population',)    ('AveOccup',)    ('Latitude',)    ('Longitude',)    ('target',)
-------------  ---------------  ---------------  ----------------  -----------------  ---------------  ---------------  ----------------  -------------
       8.3252               41          6.98413          1.02381                 322          2.55556            37.88           -122.23          4.526
       8.3014               21          6.23814          0.97188                2401          2.10984            37.86           -122.22          3.585
       7.2574               52          8.28814          1.07345                 496          2.80226            37.85           -122.24          3.521
       5.6431               52          5.81735          1.07306                 558          2.54795            37.85           -122.25          3.413
       3.8462               52          6.28185          1.08108                 565          2.18147            37.85           -122.25          3.422
       4.0368               52          4.76166          1.10363                 413          2.1399             37.85           -122.25          2.697
       3.6591               52          4.93191          0.951362               1094          2.1284             37.84           -122.25          2.992
       3.12                 52          4.79753          1.06182                1157          1.78825            37.84           -122.25          2.414
       2.0804               42          4.29412          1.11765                1206          2.02689            37.84           -122.26          2.267
       3.6912               52          4.97059          0.990196               1551          2.17227            37.84           -122.25          2.611
[20640 rows x 9 columns]

In [9]:


# Define features and target
X = train_df.drop(columns=['target'])
y = train_df['target']

# Train H2OAutoMLRegressor
aml = H2OAutoML(max_models=20, seed=1, max_runtime_secs=120)
aml.train(x=X.columns.tolist(), y=r"(\'target\',)", training_frame=train_h2o_frame)

["('MedInc',)", "('HouseAge',)", "('AveRooms',)", "('AveBedrms',)", "('Population',)", "('AveOccup',)", "('Latitude',)", "('Longitude',)", "('target',)"]


C:\Users\3aboo\AppData\Local\Temp\ipykernel_2660\153448014.py:2: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  X = train_df.drop(columns=['target'])


H2OValueError: Column (\'target\',) does not exist in the training frame

In [42]:
import h2o
from h2o.automl import H2OAutoML

# Start the H2O cluster (locally)
h2o.init()

# Import a sample binary outcome train/test set into H2O
train = h2o.import_file("https://s3.amazonaws.com/erin-data/higgs/higgs_train_10k.csv")
test = h2o.import_file("https://s3.amazonaws.com/erin-data/higgs/higgs_test_5k.csv")

# Identify predictors and response
x = train.columns
y = "response"
x.remove(y)

# For binary classification, response should be a factor
train[y] = train[y].asfactor()
test[y] = test[y].asfactor()

# Run AutoML for 20 base models
aml = H2OAutoML(max_models=20, seed=1, max_runtime_secs=60)
aml.train(x=x, y=y, training_frame=train)

# View the AutoML Leaderboard
lb = aml.leaderboard
lb.head(rows=lb.nrows)  # Print all rows instead of default (10 rows)

Checking whether there is an H2O instance running at http://localhost:54321. connected.


--------------------------  -----------------------------
H2O_cluster_uptime:         34 mins 39 secs
H2O_cluster_timezone:       Europe/Berlin
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.4
H2O_cluster_version_age:    1 month and 12 days
H2O_cluster_name:           H2O_from_python_3aboo_0mvktk
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    2.670 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.9.19 final
--------------------------  -----------------------------

ValueError: ImportFiles of 'https://s3.amazonaws.com/erin-data/higgs/higgs_train_10k.csv' failed on ['https://s3.amazonaws.com/erin-data/higgs/higgs_train_10k.csv']